- name: File Manipulation
  hosts: ans_servers
  become: true
  tasks:
    - block:
      - name: Check file exists or not
        stat:
          path: /var/tmp/saveabort.yml
        register: stat_result

      - name: Create file, if it doesnt exist already
        file:
          path: /var/tmp/saveabort.yml
          state: touch
        when: stat_result.stat.exists == False

      - name: End the play if file exists
        meta: end_play
        when: stat_result.stat.exists == True